[package]
name = "fire-cli"
version = "2.6.0"
edition = "2021"
description = "command management"
license-file = "LICENSE"
documentation = "https://docs.rs/fire-cli"
homepage = "https://github.com/gbenm/fire"
repository = "https://github.com/gbenm/fire"

[[bin]]
name = "fire"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "6.0.0"
yaml_serde = "0.10"
serde = { version = "1.0", features = ["derive"] }
rmcp = { version = "3.1.0", features = ["macros", "server", "transport-io"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "io-std"] }
serde_json = "1.0.151"
